[workspace]
members = [
  "crates/cpu_sm83",
  "crates/gb",
  "crates/cartridge",
  "crates/shared",
  "crates/ppu",
  "crates/apu",
  "crates/gb-wasm",
]
resolver = "2"

[workspace.dependencies]
gb_cpu_sm83 = { path = "crates/cpu_sm83" }
gb_cartridge = { path = "crates/cartridge" }
gb_ppu = { path = "crates/ppu" }
gb_apu = { path = "crates/apu" }
gb_shared = { path = "crates/shared" }
gb = { path = "crates/gb" }
log = { version = "0.4.17" }
anyhow = "1.0.81"
mockall = "0.12.0"
web-time = "1.1.0"
wasm-bindgen = "0.2.92"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
