[workspace]
members = [
  "crates/cpu_sm83",
  "crates/gb",
  "crates/cartridge",
  "crates/shared",
  "crates/ppu",
]

[workspace.dependencies]
gb_cpu_sm83 = { path = "crates/cpu_sm83" }
gb_cartridge = { path = "crates/cartridge" }
gb_ppu = { path = "crates/ppu" }
gb_shared = { path = "crates/shared" }
log = "0.4.17"
anyhow = "1.0.66"
