[workspace]
members = [
  "crates/cpu_sm83",
  "crates/gb",
  "crates/cartridge",
  "crates/shared",
  "crates/ppu",
  # "bin/gb_dmg",
  "crates/apu",
  "crates/blip_buf",
  "app/gb_wasm",
]
exclude = ["bin/gb_dmg"]
resolver = "2"

[workspace.dependencies]
gb_cpu_sm83 = { path = "crates/cpu_sm83" }
gb_cartridge = { path = "crates/cartridge" }
gb_ppu = { path = "crates/ppu" }
gb_apu = { path = "crates/apu" }
gb_shared = { path = "crates/shared" }
gb = { path = "crates/gb" }
blip_buf = { path = "crates/blip_buf" }
log = { version = "0.4.17", features = ["release_max_level_info"] }
anyhow = "1.0.66"
mockall = "0.12.0"
web-time = "1.1.0"
