#[derive(Debug)]
pub(crate) enum AddressingMode {
    /// Register direct
    Direct(Register),
    /// Register indirect
    Indirect(Register),
    /// PC-relative 1 byte
    PC1,
    /// PC-relative 2 bytes
    PC2,
}

#[derive(Debug)]
pub(crate) enum Condition {
    Z,
    NZ,
    C,
    NC,
}

#[derive(Debug)]
pub(crate) enum Register {
    A,
    F,
    B,
    C,
    D,
    E,
    H,
    L,
    AF,
    BC,
    DE,
    HL,
    SP,
}

#[derive(Debug)]
pub(crate) enum Instruction {
    NONE,
    NOP,
    LD(AddressingMode, AddressingMode),
    INC(AddressingMode),
    DEC(AddressingMode),
    JR(Option<Condition>),
    JP(Option<Condition>, AddressingMode),
    CALL(Option<Condition>),
    ADD(AddressingMode, AddressingMode),
    ADC(AddressingMode),
    SUB(AddressingMode),
    SBC(AddressingMode),
    PUSH(AddressingMode),
    POP(AddressingMode),
    RET(Option<Condition>),
    RETI,
    RST,
    AND(AddressingMode),
    OR(AddressingMode),
    XOR(AddressingMode),
    STOP,
    DI,
    EI,
    HALT,
    RLA,
    RRA,
    RLCA,
    RRCA,
    DAA,
    CPL,
    SCF,
    CCF,
    CP(AddressingMode),
    CB,
}

#[derive(Debug)]
pub(crate) enum CbInstruction {
    RLC,
    RRC,
    RL,
    RR,
    SLA,
    SRA,
    SWAP,
    SRL,
    BIT,
    RES,
    SET,
}

type Am = AddressingMode;
type Inst = Instruction;
const INSTRUCTIONS: [Instruction; 256] = [
    // 0x0x
    Inst::NOP,
    Inst::LD(Am::Direct(Register::BC), Am::PC2),
    Inst::LD(Am::Indirect(Register::BC), Am::Direct(Register::A)),
    Inst::INC(Am::Direct(Register::BC)),
    Inst::INC(Am::Direct(Register::B)),
    Inst::DEC(Am::Direct(Register::B)),
    Inst::LD(Am::Direct(Register::B), Am::PC1),
    Inst::RLCA,
    Inst::LD(Am::PC2, Am::Direct(Register::SP)),
    Inst::ADD(Am::Direct(Register::HL), Am::Direct(Register::BC)),
    Inst::LD(Am::Direct(Register::A), Am::Indirect(Register::BC)),
    Inst::DEC(Am::Direct(Register::BC)),
    Inst::INC(Am::Direct(Register::C)),
    Inst::DEC(Am::Direct(Register::C)),
    Inst::LD(Am::Direct(Register::C), Am::PC1),
    Inst::RRCA,
    // 0x1x
    Inst::STOP,
    Inst::LD(Am::Direct(Register::DE), Am::PC2),
    Inst::LD(Am::Indirect(Register::DE), Am::Direct(Register::A)),
    Inst::INC(Am::Direct(Register::DE)),
    Inst::INC(Am::Direct(Register::D)),
    Inst::DEC(Am::Direct(Register::D)),
    Inst::LD(Am::Direct(Register::D), Am::PC1),
    Inst::RLA,
    Inst::JR(None),
    Inst::ADD(Am::Direct(Register::HL), Am::Direct(Register::DE)),
    Inst::LD(Am::Direct(Register::A), Am::Indirect(Register::DE)),
    Inst::DEC(Am::Direct(Register::DE)),
    Inst::INC(Am::Direct(Register::E)),
    Inst::DEC(Am::Direct(Register::E)),
    Inst::LD(Am::Direct(Register::E), Am::PC1),
    Inst::RRA,
    // 0x2x
    Inst::JR(Some(Condition::NZ)),
    Inst::LD(Am::Direct(Register::HL), Am::PC2),
    Inst::LD(Am::Indirect(Register::HL), Am::Direct(Register::A)),
    Inst::INC(Am::Direct(Register::HL)),
    Inst::INC(Am::Direct(Register::H)),
    Inst::DEC(Am::Direct(Register::H)),
    Inst::LD(Am::Direct(Register::H), Am::PC1),
    Inst::DAA,
    Inst::JR(Some(Condition::Z)),
    Inst::ADD(Am::Direct(Register::HL), Am::Direct(Register::HL)),
    Inst::LD(Am::Direct(Register::A), Am::Indirect(Register::HL)),
    Inst::DEC(Am::Direct(Register::HL)),
    Inst::INC(Am::Direct(Register::L)),
    Inst::DEC(Am::Direct(Register::L)),
    Inst::LD(Am::Direct(Register::L), Am::PC1),
    Inst::CPL,
    // 0x3x
    Inst::JR(Some(Condition::NC)),
    Inst::LD(Am::Direct(Register::SP), Am::PC2),
    Inst::LD(Am::Indirect(Register::HL), Am::Direct(Register::A)),
    Inst::INC(Am::Direct(Register::SP)),
    Inst::INC(Am::Indirect(Register::HL)),
    Inst::DEC(Am::Indirect(Register::HL)),
    Inst::LD(Am::Indirect(Register::HL), Am::PC1),
    Inst::SCF,
    Inst::JR(Some(Condition::C)),
    Inst::ADD(Am::Direct(Register::HL), Am::Direct(Register::SP)),
    Inst::LD(Am::Direct(Register::A), Am::Indirect(Register::HL)),
    Inst::DEC(Am::Direct(Register::SP)),
    Inst::INC(Am::Direct(Register::A)),
    Inst::DEC(Am::Direct(Register::A)),
    Inst::LD(Am::Direct(Register::A), Am::PC1),
    Inst::CCF,
    // 0x4x
    Inst::LD(Am::Direct(Register::B), Am::Direct(Register::B)),
    Inst::LD(Am::Direct(Register::B), Am::Direct(Register::C)),
    Inst::LD(Am::Direct(Register::B), Am::Direct(Register::D)),
    Inst::LD(Am::Direct(Register::B), Am::Direct(Register::E)),
    Inst::LD(Am::Direct(Register::B), Am::Direct(Register::H)),
    Inst::LD(Am::Direct(Register::B), Am::Direct(Register::L)),
    Inst::LD(Am::Direct(Register::B), Am::Indirect(Register::HL)),
    Inst::LD(Am::Direct(Register::B), Am::Direct(Register::A)),
    Inst::LD(Am::Direct(Register::C), Am::Direct(Register::B)),
    Inst::LD(Am::Direct(Register::C), Am::Direct(Register::C)),
    Inst::LD(Am::Direct(Register::C), Am::Direct(Register::D)),
    Inst::LD(Am::Direct(Register::C), Am::Direct(Register::E)),
    Inst::LD(Am::Direct(Register::C), Am::Direct(Register::H)),
    Inst::LD(Am::Direct(Register::C), Am::Direct(Register::L)),
    Inst::LD(Am::Direct(Register::C), Am::Indirect(Register::HL)),
    Inst::LD(Am::Direct(Register::C), Am::Direct(Register::A)),
    // 0x5x
    Inst::LD(Am::Direct(Register::D), Am::Direct(Register::B)),
    Inst::LD(Am::Direct(Register::D), Am::Direct(Register::C)),
    Inst::LD(Am::Direct(Register::D), Am::Direct(Register::D)),
    Inst::LD(Am::Direct(Register::D), Am::Direct(Register::E)),
    Inst::LD(Am::Direct(Register::D), Am::Direct(Register::H)),
    Inst::LD(Am::Direct(Register::D), Am::Direct(Register::L)),
    Inst::LD(Am::Direct(Register::D), Am::Indirect(Register::HL)),
    Inst::LD(Am::Direct(Register::D), Am::Direct(Register::A)),
    Inst::LD(Am::Direct(Register::E), Am::Direct(Register::B)),
    Inst::LD(Am::Direct(Register::E), Am::Direct(Register::C)),
    Inst::LD(Am::Direct(Register::E), Am::Direct(Register::D)),
    Inst::LD(Am::Direct(Register::E), Am::Direct(Register::E)),
    Inst::LD(Am::Direct(Register::E), Am::Direct(Register::H)),
    Inst::LD(Am::Direct(Register::E), Am::Direct(Register::L)),
    Inst::LD(Am::Direct(Register::E), Am::Indirect(Register::HL)),
    Inst::LD(Am::Direct(Register::E), Am::Direct(Register::A)),
    // 0x6x
    Inst::LD(Am::Direct(Register::H), Am::Direct(Register::B)),
    Inst::LD(Am::Direct(Register::H), Am::Direct(Register::C)),
    Inst::LD(Am::Direct(Register::H), Am::Direct(Register::D)),
    Inst::LD(Am::Direct(Register::H), Am::Direct(Register::E)),
    Inst::LD(Am::Direct(Register::H), Am::Direct(Register::H)),
    Inst::LD(Am::Direct(Register::H), Am::Direct(Register::L)),
    Inst::LD(Am::Direct(Register::H), Am::Indirect(Register::HL)),
    Inst::LD(Am::Direct(Register::H), Am::Direct(Register::A)),
    Inst::LD(Am::Direct(Register::L), Am::Direct(Register::B)),
    Inst::LD(Am::Direct(Register::L), Am::Direct(Register::C)),
    Inst::LD(Am::Direct(Register::L), Am::Direct(Register::D)),
    Inst::LD(Am::Direct(Register::L), Am::Direct(Register::E)),
    Inst::LD(Am::Direct(Register::L), Am::Direct(Register::H)),
    Inst::LD(Am::Direct(Register::L), Am::Direct(Register::L)),
    Inst::LD(Am::Direct(Register::L), Am::Indirect(Register::HL)),
    Inst::LD(Am::Direct(Register::L), Am::Direct(Register::A)),
    // 0x7x
    Inst::LD(Am::Indirect(Register::HL), Am::Direct(Register::B)),
    Inst::LD(Am::Indirect(Register::HL), Am::Direct(Register::C)),
    Inst::LD(Am::Indirect(Register::HL), Am::Direct(Register::D)),
    Inst::LD(Am::Indirect(Register::HL), Am::Direct(Register::E)),
    Inst::LD(Am::Indirect(Register::HL), Am::Direct(Register::H)),
    Inst::LD(Am::Indirect(Register::HL), Am::Direct(Register::L)),
    Inst::HALT,
    Inst::LD(Am::Indirect(Register::HL), Am::Direct(Register::A)),
    Inst::LD(Am::Direct(Register::A), Am::Direct(Register::B)),
    Inst::LD(Am::Direct(Register::A), Am::Direct(Register::C)),
    Inst::LD(Am::Direct(Register::A), Am::Direct(Register::D)),
    Inst::LD(Am::Direct(Register::A), Am::Direct(Register::E)),
    Inst::LD(Am::Direct(Register::A), Am::Direct(Register::H)),
    Inst::LD(Am::Direct(Register::A), Am::Direct(Register::L)),
    Inst::LD(Am::Direct(Register::A), Am::Indirect(Register::HL)),
    Inst::LD(Am::Direct(Register::A), Am::Direct(Register::A)),
    // 0x8x
    Inst::ADD(Am::Direct(Register::A), Am::Direct(Register::B)),
    Inst::ADD(Am::Direct(Register::A), Am::Direct(Register::C)),
    Inst::ADD(Am::Direct(Register::A), Am::Direct(Register::D)),
    Inst::ADD(Am::Direct(Register::A), Am::Direct(Register::E)),
    Inst::ADD(Am::Direct(Register::A), Am::Direct(Register::H)),
    Inst::ADD(Am::Direct(Register::A), Am::Direct(Register::L)),
    Inst::ADD(Am::Direct(Register::A), Am::Indirect(Register::HL)),
    Inst::ADD(Am::Direct(Register::A), Am::Direct(Register::A)),
    Inst::ADC(Am::Direct(Register::B)),
    Inst::ADC(Am::Direct(Register::C)),
    Inst::ADC(Am::Direct(Register::D)),
    Inst::ADC(Am::Direct(Register::E)),
    Inst::ADC(Am::Direct(Register::H)),
    Inst::ADC(Am::Direct(Register::L)),
    Inst::ADC(Am::Indirect(Register::HL)),
    Inst::ADC(Am::Direct(Register::A)),
    // 0x9x
    Inst::SUB(Am::Direct(Register::B)),
    Inst::SUB(Am::Direct(Register::C)),
    Inst::SUB(Am::Direct(Register::D)),
    Inst::SUB(Am::Direct(Register::E)),
    Inst::SUB(Am::Direct(Register::H)),
    Inst::SUB(Am::Direct(Register::L)),
    Inst::SUB(Am::Indirect(Register::HL)),
    Inst::SUB(Am::Direct(Register::A)),
    Inst::SBC(Am::Direct(Register::B)),
    Inst::SBC(Am::Direct(Register::C)),
    Inst::SBC(Am::Direct(Register::D)),
    Inst::SBC(Am::Direct(Register::E)),
    Inst::SBC(Am::Direct(Register::H)),
    Inst::SBC(Am::Direct(Register::L)),
    Inst::SBC(Am::Indirect(Register::HL)),
    Inst::SBC(Am::Direct(Register::A)),
    // 0xAx
    Inst::AND(Am::Direct(Register::B)),
    Inst::AND(Am::Direct(Register::C)),
    Inst::AND(Am::Direct(Register::D)),
    Inst::AND(Am::Direct(Register::E)),
    Inst::AND(Am::Direct(Register::H)),
    Inst::AND(Am::Direct(Register::L)),
    Inst::AND(Am::Indirect(Register::HL)),
    Inst::AND(Am::Direct(Register::A)),
    Inst::XOR(Am::Direct(Register::B)),
    Inst::XOR(Am::Direct(Register::C)),
    Inst::XOR(Am::Direct(Register::D)),
    Inst::XOR(Am::Direct(Register::E)),
    Inst::XOR(Am::Direct(Register::H)),
    Inst::XOR(Am::Direct(Register::L)),
    Inst::XOR(Am::Indirect(Register::HL)),
    Inst::XOR(Am::Direct(Register::A)),
    // 0xBx
    Inst::OR(Am::Direct(Register::B)),
    Inst::OR(Am::Direct(Register::C)),
    Inst::OR(Am::Direct(Register::D)),
    Inst::OR(Am::Direct(Register::E)),
    Inst::OR(Am::Direct(Register::H)),
    Inst::OR(Am::Direct(Register::L)),
    Inst::OR(Am::Indirect(Register::HL)),
    Inst::OR(Am::Direct(Register::A)),
    Inst::CP(Am::Direct(Register::B)),
    Inst::CP(Am::Direct(Register::C)),
    Inst::CP(Am::Direct(Register::D)),
    Inst::CP(Am::Direct(Register::E)),
    Inst::CP(Am::Direct(Register::H)),
    Inst::CP(Am::Direct(Register::L)),
    Inst::CP(Am::Indirect(Register::HL)),
    Inst::CP(Am::Direct(Register::A)),
    // 0xCx
    Inst::RET(Some(Condition::NZ)),
    Inst::POP(Am::Direct(Register::BC)),
    Inst::JP(Some(Condition::NZ), Am::PC2),
    Inst::JP(None, Am::PC2),
    Inst::CALL(Some(Condition::NZ)),
    Inst::PUSH(Am::Direct(Register::BC)),
    Inst::ADD(Am::Direct(Register::A), Am::PC1),
    Inst::RST,
    Inst::RET(Some(Condition::Z)),
    Inst::RET(None),
    Inst::JP(Some(Condition::Z), Am::PC2),
    Inst::CB,
    Inst::CALL(Some(Condition::Z)),
    Inst::CALL(None),
    Inst::ADC(Am::PC1),
    Inst::RST,
    // 0xDx
    Inst::RET(Some(Condition::NC)),
    Inst::POP(Am::Direct(Register::DE)),
    Inst::JP(Some(Condition::NZ), Am::PC2),
    Inst::NONE,
    Inst::CALL(Some(Condition::NC)),
    Inst::PUSH(Am::Direct(Register::DE)),
    Inst::SUB(Am::PC1),
    Inst::RST,
    Inst::RET(Some(Condition::C)),
    Inst::RETI,
    Inst::JP(Some(Condition::C), Am::PC2),
    Inst::NONE,
    Inst::CALL(Some(Condition::C)),
    Inst::NONE,
    Inst::SBC(Am::PC1),
    Inst::RST,
    // 0xEx
    Inst::LD(Am::PC1, Am::Direct(Register::A)),
    Inst::POP(Am::Direct(Register::HL)),
    Inst::LD(Am::Direct(Register::C), Am::Direct(Register::A)),
    Inst::NONE,
    Inst::NONE,
    Inst::PUSH(Am::Direct(Register::HL)),
    Inst::AND(Am::PC1),
    Inst::RST,
    Inst::ADD(Am::Direct(Register::SP), Am::PC1),
    Inst::JP(None, Am::Indirect(Register::HL)),
    Inst::LD(Am::PC2, Am::Direct(Register::A)),
    Inst::NONE,
    Inst::NONE,
    Inst::NONE,
    Inst::XOR(Am::PC1),
    Inst::RST,
    // 0xFx
    Inst::LD(Am::Direct(Register::A), Am::PC2),
    Inst::POP(Am::Direct(Register::AF)),
    Inst::LD(Am::Direct(Register::A), Am::Direct(Register::C)),
    Inst::DI,
    Inst::NONE,
    Inst::PUSH(Am::Direct(Register::AF)),
    Inst::OR(Am::PC1),
    Inst::RST,
    Inst::LD(Am::Direct(Register::HL), Am::Direct(Register::SP)),
    Inst::LD(Am::Direct(Register::SP), Am::Direct(Register::HL)),
    Inst::LD(Am::Direct(Register::A), Am::PC2),
    Inst::EI,
    Inst::NONE,
    Inst::NONE,
    Inst::CP(Am::PC1),
    Inst::RST,
];

pub(crate) fn get_instruction(opcode: u8) -> &'static Instruction {
    INSTRUCTIONS.get(opcode as usize).unwrap()
}
