[package]
name = "gb_dmg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gb = { workspace = true }
gb_shared = { workspace = true }
log = { workspace = true }
anyhow = { workspace = true }
env_logger = "0.9.1"
pixels = "0.13.0"
winit = { version = "0.29.4", default-features = false, features = [
  "rwh_05",
  "x11",
  "wayland",
  "wayland-dlopen",
  "wayland-csd-adwaita",
] }
winit_input_helper = "0.15.1"
chrono = "0.4.31"
# use xinput for fixing no events on Windows
# https://gitlab.com/gilrs-project/gilrs/-/issues/136
gilrs = { version = "0.10.6", default-features = false, features = ["xinput"] }
cpal = "0.15.2"

[[bin]]
name = "gb"
path = "./src/main.rs"
