build:
  wasm-pack build --release --out-dir npm --target web --mode no-install
build-dev:
  # As a workaround now. Make sure run `build` first to generate the `package.json` file.
  cargo build --target wasm32-unknown-unknown --release && wasm-bindgen --keep-debug --web --out-dir npm ../../target/wasm32-unknown-unknown/release/gb_wasm.wasm
