[package]
name = "gb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpu_sm83 = { path = "../cpu_sm83" }
cartridge = { path = "../cartridge" }
io = { path = "../io" }
log = "0.4.17"
env_logger = "0.9.1"
shared = { path = "../shared" }
ppu = { path = "../ppu" }