[package]
name = "gb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpu_sm83 = { workspace = true }
cartridge = { workspace = true }
io = { workspace = true }
log = { workspace = true }
env_logger = "0.9.1"
shared = { workspace = true }
ppu = { workspace = true }
