export { default as IconDelete } from "./delete_forever.svg?react";
export { default as IconPlay } from "./play_arrow.svg?react";
export { default as IconHistory } from "./manage_history.svg?react";
export { default as IconAdd } from "./playlist_add.svg?react";
export { default as IconSettings } from "./settings.svg?react";
export { default as IconFullscreen } from "./fullscreen.svg?react";
export { default as IconFullscreenExit } from "./fullscreen_exit.svg?react";
export { default as IconFileDownload } from "./file_download.svg?react";
export { default as IconFileUpload } from "./file_upload.svg?react";
